import { env } from "@/env";

// CA
export const ISSUE_ADDRESS = env.NEXT_PUBLIC_ISSUE_ADDRESS as `0x${string}`;
export const MANTLE_USD_ADDRESS =
  env.NEXT_PUBLIC_MANTLEUSD_ADDRESS as `0x${string}`;

// ABI
export const ISSUE_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_validator", type: "address" },
      { internalType: "address", name: "_bountyToken", type: "address" },
      { internalType: "address", name: "_avsContract", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ClaimAlreadyValidated", type: "error" },
  { inputs: [], name: "DeadlinePassed", type: "error" },
  { inputs: [], name: "InvalidBountyAmount", type: "error" },
  { inputs: [], name: "InvalidClaimIndex", type: "error" },
  { inputs: [], name: "InvalidDeadline", type: "error" },
  { inputs: [], name: "InvalidIssueId", type: "error" },
  { inputs: [], name: "InvalidMaxClaims", type: "error" },
  { inputs: [], name: "IssueClosed", type: "error" },
  { inputs: [], name: "IssueStillActive", type: "error" },
  { inputs: [], name: "MaximumClaimsReached", type: "error" },
  { inputs: [], name: "OnlyOwner", type: "error" },
  { inputs: [], name: "PRAlreadyUsed", type: "error" },
  { inputs: [], name: "PRNotMerged", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "AVSEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "issueId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "claimIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
    ],
    name: "AVSTaskCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "issueId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "claimIndex",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "developer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "ClaimValidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "issueId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FundsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "issueId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bountyAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxClaims",
        type: "uint256",
      },
    ],
    name: "IssueCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "issueId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "developer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "prLink",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bountyAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RewardClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "avsContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "avsEnabled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "bountyToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "claimCounts",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_issueId", type: "uint256" },
      { internalType: "string", name: "_prLink", type: "string" },
      { internalType: "bool", name: "_isMerged", type: "bool" },
      { internalType: "string", name: "_accessToken", type: "string" },
    ],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "claims",
    outputs: [
      { internalType: "string", name: "prLink", type: "string" },
      { internalType: "bool", name: "isMerged", type: "bool" },
      { internalType: "address", name: "developer", type: "address" },
      { internalType: "bool", name: "isValidated", type: "bool" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "string", name: "accessToken", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_githubProjectId", type: "string" },
      { internalType: "uint256", name: "_bountyAmount", type: "uint256" },
      { internalType: "string", name: "_projectName", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
      { internalType: "string", name: "_repoLink", type: "string" },
      { internalType: "uint256", name: "_deadline", type: "uint256" },
      { internalType: "uint256", name: "_maxClaims", type: "uint256" },
    ],
    name: "createIssue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllIssues",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "string", name: "githubProjectId", type: "string" },
          { internalType: "uint256", name: "bountyAmount", type: "uint256" },
          { internalType: "string", name: "projectName", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "string", name: "repoLink", type: "string" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "isOpen", type: "bool" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "maxClaims", type: "uint256" },
          { internalType: "uint256", name: "currentClaims", type: "uint256" },
        ],
        internalType: "struct IIssuesClaim.Issue[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_issueId", type: "uint256" },
      { internalType: "uint256", name: "_claimIndex", type: "uint256" },
    ],
    name: "getClaimResponse",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "issueId", type: "uint256" },
          { internalType: "string", name: "prLink", type: "string" },
          { internalType: "uint256", name: "bountyAmount", type: "uint256" },
          { internalType: "address", name: "developer", type: "address" },
          { internalType: "bool", name: "isApproved", type: "bool" },
          { internalType: "bool", name: "isValidated", type: "bool" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
        ],
        internalType: "struct IIssuesClaim.Response",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_issueId", type: "uint256" }],
    name: "getIssueDetails",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "string", name: "githubProjectId", type: "string" },
          { internalType: "uint256", name: "bountyAmount", type: "uint256" },
          { internalType: "string", name: "projectName", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "string", name: "repoLink", type: "string" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "isOpen", type: "bool" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "maxClaims", type: "uint256" },
          { internalType: "uint256", name: "currentClaims", type: "uint256" },
        ],
        internalType: "struct IIssuesClaim.Issue",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "issueCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "issues",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "githubProjectId", type: "string" },
      { internalType: "uint256", name: "bountyAmount", type: "uint256" },
      { internalType: "string", name: "projectName", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "string", name: "repoLink", type: "string" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "bool", name: "isOpen", type: "bool" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "maxClaims", type: "uint256" },
      { internalType: "uint256", name: "currentClaims", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_enabled", type: "bool" }],
    name: "setAVSEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newAVS", type: "address" }],
    name: "updateAVSContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "usedPRLinks",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_issueId", type: "uint256" },
      { internalType: "uint256", name: "_claimIndex", type: "uint256" },
      { internalType: "bool", name: "_isValid", type: "bool" },
    ],
    name: "validateClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "validator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_prLink", type: "string" }],
    name: "verifyMergeStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_issueId", type: "uint256" }],
    name: "withdrawRemainingFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export const MANTLE_USD_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "allowance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientAllowance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "approver", type: "address" }],
    name: "ERC20InvalidApprover",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "receiver", type: "address" }],
    name: "ERC20InvalidReceiver",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "sender", type: "address" }],
    name: "ERC20InvalidSender",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "spender", type: "address" }],
    name: "ERC20InvalidSpender",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
